name: Deploy
on: { push: { tags: [ 'v*' ] } }
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: cluebotng/utilities
          ref: main

      - uses: cluebotng/ci-execute-fabric@main
        with:
          task: deploy-report
          release: ${{ github.ref }}
          ssh_key: ${{ secrets.CI_SSH_KEY }}
